version: "3.7"

services:
  social-login-db:
    image: mongo
    container_name: social-login-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=users
    volumes:
      - /data/db
    ports:
      - 27022:27017
    networks:
      - social-login-network
    logging:
      driver: none

  social-login-app:
    build:
      context: .
    container_name: social-login-app
    command: npm run dev
    environment:
      - ENVIRONMENT=dev
      - MONGO_USERNAME=username
      - MONGO_PASSWORD=password
      - MONGO_DATABASE_NAME=users
      - MONGO_HOST=social-login-db
      - MONGO_PORT=27017
      - TWITTER_KEY=P077ZnUB6QSW0EwyAdbqZ4h8U
      - TWITTER_SECRET=CfKECd3vHVu2sPYKmS3FAEZ2HnKqV4UQTXy5a1Fg0wNvH7ARXw
      - FACEBOOK_CLIENT_ID=266417798491983
      - FACEBOOK_SECRET=617d8ac408f44f31e8555fddc7270b38
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:3600
      - 9229:9229
    networks:
      - social-login-network

networks:
  social-login-network:
